# Generated by Django 5.0.7 on 2024-08-19 08:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('model_year', models.PositiveIntegerField(default=2024)),
                ('color', models.CharField(choices=[('red', 'red'), ('yellow', 'yellow'), ('blue', 'blue'), ('white', 'white')], max_length=6)),
                ('company_name', models.CharField(max_length=50)),
                ('is_bifuel', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_name', models.CharField(max_length=100)),
                ('time', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=20)),
                ('imdb_rate', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='loginlogout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('login', 'login'), ('logout', 'logout')], max_length=50)),
                ('user_id', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(blank=True, max_length=50, null=True)),
                ('auth_code', models.CharField(blank=True, max_length=20, null=True)),
                ('ip_address', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('Groceries', 'Groceries'), ('snacks', 'snacks'), ('sanitary', 'sanitary'), ('vegetable', 'vegetable')], max_length=10)),
                ('product_name', models.CharField(max_length=200)),
                ('stock', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)])),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000)])),
                ('brand', models.CharField(choices=[('Tabarok', 'Tabarok'), ('Hayley', 'Hayley'), ('Chi TOZ', 'Chi TOZ')], max_length=10)),
                ('expiration_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='StreamContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('time', models.IntegerField()),
                ('problem', models.CharField(choices=[('noproblem', 'noproblem'), ('nofile', 'nofile'), ('videoerror', 'videoerror')], max_length=50)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('hide', models.BooleanField(default=False)),
                ('version', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=50)),
                ('birth', models.PositiveIntegerField()),
                ('mother_name', models.CharField(blank=True, max_length=50, null=True)),
                ('average_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=10)),
                ('level', models.CharField(choices=[('primary', 'primary'), ('middle', 'middle'), ('high', 'high')], default='primary', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('big', 'big'), ('thumb', 'thumb')], max_length=50)),
                ('file_name', models.CharField(max_length=255)),
                ('staff_id', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnsuccessfullLoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(max_length=50)),
                ('Reason', models.CharField(choices=[('wrong_password', 'Wrong password'), ('wrong_username', 'Wrong username')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=100)),
                ('family', models.CharField(default='Unknown', max_length=100)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserWatchedLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('stream_content_id', models.CharField(max_length=50)),
                ('hash', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=50)),
                ('platform', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('voiece_channel_number', models.IntegerField(blank=True, null=True)),
                ('with_subtitle', models.BooleanField(default=False)),
                ('quality_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=100)),
                ('amount', models.IntegerField()),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('size', models.CharField(choices=[('small', 'small'), ('medum', 'medum')], max_length=50)),
                ('color', models.CharField(choices=[('red', 'red'), ('yellow', 'yellow'), ('blue', 'blue')], max_length=6)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.category')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_productimage', to='user.usermodel')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='user.usermodel'),
        ),
    ]
